import { db } from "@workspace/db";
import {
  membersTable, connectionsTable,
  commoditiesTable, priceHistoryTable, buyersTable, marketAlertsTable,
  opportunitiesTable, projectsTable, forumThreadsTable,
  eventsTable, resourcesTable, successStoriesTable, mentorsTable, knowledgeTable,
} from "@workspace/db";

async function seed() {
  console.log("🌱 Seeding EAAPA database...");

  // Members
  console.log("Adding members...");
  await db.insert(membersTable).values([
    { name: "Amara Nkosi", role: "agripreneur", sector: "Horticulture", region: "Central Kenya", country: "Kenya", commodity: "Avocado", businessType: "Export Farming", bio: "Leading avocado farmer with 200 acres under cultivation, exporting to EU markets.", isVerified: true, revenueUsd: "480000", jobsCreated: 85, yieldTons: "1200", growthPercent: "32" },
    { name: "David Ochieng", role: "agripreneur", sector: "Dairy", region: "Rift Valley", country: "Kenya", commodity: "Milk", businessType: "Dairy Processing", bio: "Pioneering dairy farmer running a processing cooperative with 300 members.", isVerified: true, revenueUsd: "320000", jobsCreated: 120, yieldTons: "800", growthPercent: "28" },
    { name: "Grace Atuhaire", role: "agripreneur", sector: "Horticulture", region: "Central Uganda", country: "Uganda", commodity: "Banana", businessType: "Processing & Export", bio: "Banana processing entrepreneur connecting smallholder farmers to export markets.", isVerified: true, revenueUsd: "195000", jobsCreated: 45, yieldTons: "600", growthPercent: "41" },
    { name: "Samuel Kariuki", role: "investor", sector: "Agribusiness", region: "Nairobi", country: "Kenya", commodity: "Multiple", businessType: "Venture Capital", bio: "Impact investor focused on agricultural transformation across East Africa.", isVerified: true, revenueUsd: "0", jobsCreated: 0 },
    { name: "Fatuma Hassan", role: "mentor", sector: "Export Markets", region: "Mombasa", country: "Kenya", commodity: "Macadamia", businessType: "Consultancy", bio: "20 years experience in agricultural export trade and market development.", isVerified: true, revenueUsd: "150000", jobsCreated: 12 },
    { name: "Jean-Pierre Nziza", role: "agripreneur", sector: "Coffee", region: "Kigali", country: "Rwanda", commodity: "Coffee", businessType: "Specialty Coffee", bio: "Specialty coffee producer selling direct to European and North American buyers.", isVerified: true, revenueUsd: "280000", jobsCreated: 38, yieldTons: "45", growthPercent: "55" },
    { name: "Tigist Bekele", role: "agripreneur", sector: "Floriculture", region: "Addis Ababa", country: "Ethiopia", commodity: "Flowers", businessType: "Cut Flower Export", bio: "Ethiopia's rising star in floriculture, supplying premium cut flowers to Europe.", isVerified: true, revenueUsd: "395000", jobsCreated: 210, growthPercent: "67" },
    { name: "Moses Wanjala", role: "agripreneur", sector: "Cereals", region: "Western Kenya", country: "Kenya", commodity: "Maize", businessType: "Grain Trading", bio: "Grain aggregator connecting 500+ smallholder farmers to national food processors.", isVerified: false, revenueUsd: "125000", jobsCreated: 22, yieldTons: "2000", growthPercent: "18" },
    { name: "Immaculate Nakitto", role: "partner", sector: "Finance", region: "Kampala", country: "Uganda", commodity: "Multiple", businessType: "Microfinance", bio: "Agri-microfinance specialist providing working capital to smallholder farmers.", isVerified: true, revenueUsd: "0", jobsCreated: 0 },
    { name: "Charles Mutua", role: "agripreneur", sector: "Aquaculture", region: "Lake Victoria Basin", country: "Kenya", commodity: "Fish", businessType: "Fish Farming", bio: "Tilapia and catfish farmer scaling up cage aquaculture on Lake Victoria.", isVerified: true, revenueUsd: "98000", jobsCreated: 30, yieldTons: "85", growthPercent: "45" },
    { name: "Asha Daud", role: "agripreneur", sector: "Spices", region: "Coastal Kenya", country: "Kenya", commodity: "Vanilla", businessType: "Specialty Crops", bio: "Premium vanilla cultivator supplying international food and fragrance companies.", isVerified: true, revenueUsd: "220000", jobsCreated: 18, growthPercent: "89" },
    { name: "Hassan Abdi", role: "investor", sector: "Infrastructure", region: "Nairobi", country: "Kenya", commodity: "Multiple", businessType: "Private Equity", bio: "Infrastructure investor focusing on cold chain and post-harvest loss reduction.", isVerified: true, revenueUsd: "0", jobsCreated: 0 },
    { name: "Zawadi Mwangi", role: "agripreneur", sector: "Macadamia", region: "Mt. Kenya", country: "Kenya", commodity: "Macadamia", businessType: "Nut Processing", bio: "Macadamia nut processor with EU and US export certifications.", isVerified: true, revenueUsd: "340000", jobsCreated: 65, yieldTons: "180", growthPercent: "38" },
    { name: "Benedicte Uwimana", role: "mentor", sector: "Agri-Finance", region: "Kigali", country: "Rwanda", commodity: "Coffee", businessType: "Financial Advisory", bio: "Coffee cooperative development expert with World Bank and UN FAO experience.", isVerified: true, revenueUsd: "0", jobsCreated: 0 },
    { name: "Peter Kamau", role: "company", sector: "AgriTech", region: "Nairobi", country: "Kenya", commodity: "Multiple", businessType: "Technology Platform", bio: "Co-founder of an AI-powered precision agriculture platform serving 10,000+ farmers.", isVerified: true, revenueUsd: "1200000", jobsCreated: 48 },
  ]).onConflictDoNothing();

  // Commodities
  console.log("Adding commodities...");
  const commodityIds = await db.insert(commoditiesTable).values([
    { name: "Avocado (Hass)", category: "Horticulture", avgPrice: "180", currency: "KES", demandLevel: "Very High", marketSizeUsd: "450000000", topBuyers: ["Greenyard NL", "Dole UK", "METRO AG", "Albert Heijn"], trend: "up", marketHealth: "Green", region: "Central Kenya", isExport: true, isOrganic: false, priceChange7d: "4.2", priceChange30d: "12.8", globalPrice: "850", demandGrowthPercent: "18", importRegions: ["Netherlands", "Germany", "France", "UK"], exportRegions: ["Kenya", "Ethiopia", "Uganda"], variety: "Hass", qualityStandards: ["GlobalGAP", "Grade A min 180g"], packaging: ["4.5kg Box", "Bulk Pallet"], certifications: ["GlobalGAP", "Tesco Nurture", "Organic EU"], exportRequirements: ["Phytosanitary Certificate", "KEPHIS Inspection", "COO"], tonsPerYear: "280000", exportRoutes: ["Nairobi → Schiphol", "Mombasa → Rotterdam", "Nairobi → Dubai → EU"], avgDeliveryDays: 5, costPerTon: "320", opportunityScore: 94, suggestedAcreage: "50", yieldProjectionTons: "180", revenueProjectionUsd: "95000" },
    { name: "Coffee (Arabica)", category: "Beverages", avgPrice: "950", currency: "KES", demandLevel: "High", marketSizeUsd: "320000000", topBuyers: ["Starbucks", "Nespresso", "Lavazza", "JDE Peet's"], trend: "up", marketHealth: "Green", region: "Central Kenya", isExport: true, isOrganic: true, priceChange7d: "2.1", priceChange30d: "8.5", globalPrice: "4800", demandGrowthPercent: "12", importRegions: ["USA", "Germany", "Japan", "Italy"], exportRegions: ["Kenya", "Ethiopia", "Rwanda", "Uganda"], variety: "SL28 / SL34", qualityStandards: ["Grade AA", "Cup score 85+"], packaging: ["60kg GrainPro Bags", "Vacuum Sealed Specialty"], certifications: ["Fair Trade", "Organic", "Rainforest Alliance"], exportRequirements: ["Coffee Board License", "Export Certificate", "Quality Certificate"], tonsPerYear: "45000", exportRoutes: ["Nairobi → Hamburg", "Mombasa → Southampton"], avgDeliveryDays: 28, costPerTon: "280", opportunityScore: 88, suggestedAcreage: "20", yieldProjectionTons: "15", revenueProjectionUsd: "120000" },
    { name: "Macadamia", category: "Tree Nuts", avgPrice: "680", currency: "KES", demandLevel: "Very High", marketSizeUsd: "180000000", topBuyers: ["Mauna Loa", "Nuti Free", "Happyway", "Bioprogreen"], trend: "up", marketHealth: "Green", region: "Mt. Kenya", isExport: true, isOrganic: false, priceChange7d: "3.8", priceChange30d: "15.2", globalPrice: "3200", demandGrowthPercent: "22", importRegions: ["China", "USA", "Germany", "Japan"], exportRegions: ["Kenya", "Tanzania", "Malawi"], variety: "DUDH / KRG", qualityStandards: ["Grade 0 / 1 / 2", "Min 34% NIS"], packaging: ["25kg PP Bags", "Kernel Vacuum"], certifications: ["KEPHIS", "FDA Registered", "GlobalGAP"], exportRequirements: ["Phytosanitary", "Fumigation Certificate", "COO"], tonsPerYear: "58000", exportRoutes: ["Nairobi → Shanghai", "Mombasa → Los Angeles"], avgDeliveryDays: 21, costPerTon: "380", opportunityScore: 91, suggestedAcreage: "30", yieldProjectionTons: "25", revenueProjectionUsd: "135000" },
    { name: "Fresh Milk", category: "Dairy", avgPrice: "55", currency: "KES", demandLevel: "High", marketSizeUsd: "820000000", topBuyers: ["Brookside", "New KCC", "Daima Foods", "Tuzo"], trend: "stable", marketHealth: "Yellow", region: "Rift Valley", isExport: false, isOrganic: false, priceChange7d: "0.5", priceChange30d: "2.1", globalPrice: "65", demandGrowthPercent: "6", importRegions: ["Kenya (Domestic)"], exportRegions: ["Kenya", "Uganda"], variety: "Friesian / Ayrshire", qualityStandards: ["TBC <50K", "Fat 3.5%+"], packaging: ["20L Can", "1L Sachets", "UHT Carton"], certifications: ["KEBS", "KDB License"], exportRequirements: ["Health Certificate", "KDB Export Permit"], tonsPerYear: "4200000", exportRoutes: ["Nairobi Distribution", "Mombasa Coastal"], avgDeliveryDays: 1, costPerTon: "55", opportunityScore: 72, suggestedAcreage: "5", yieldProjectionTons: "18", revenueProjectionUsd: "42000" },
    { name: "French Beans", category: "Horticulture", avgPrice: "140", currency: "KES", demandLevel: "High", marketSizeUsd: "95000000", topBuyers: ["Tesco UK", "Sainsbury's", "Carrefour FR", "SPAR"], trend: "stable", marketHealth: "Green", region: "Central Kenya", isExport: true, isOrganic: false, priceChange7d: "-1.2", priceChange30d: "3.4", globalPrice: "580", demandGrowthPercent: "8", importRegions: ["UK", "France", "Netherlands", "Germany"], exportRegions: ["Kenya", "Zimbabwe"], variety: "Amy / Serengeti / Climax", qualityStandards: ["Grade A 4-8mm diameter", "Max 12cm length"], packaging: ["100g Retail Pack", "5kg Bulk Box"], certifications: ["GlobalGAP", "Tesco Nurture", "LEAF"], exportRequirements: ["Phytosanitary", "Maximum Residue Level Test", "COO"], tonsPerYear: "22000", exportRoutes: ["Nairobi → Heathrow", "Nairobi → Paris CDG"], avgDeliveryDays: 3, costPerTon: "420", opportunityScore: 79, suggestedAcreage: "10", yieldProjectionTons: "32", revenueProjectionUsd: "58000" },
    { name: "Maize", category: "Cereals", avgPrice: "38", currency: "KES", demandLevel: "High", marketSizeUsd: "1200000000", topBuyers: ["UNGA Group", "East Africa Grains", "WFP", "Kenya Breweries"], trend: "up", marketHealth: "Yellow", region: "Western Kenya", isExport: false, isOrganic: false, priceChange7d: "1.8", priceChange30d: "6.2", globalPrice: "180", demandGrowthPercent: "4", importRegions: ["Kenya (Domestic)", "Uganda", "Tanzania"], exportRegions: ["Kenya", "Uganda", "Tanzania"], variety: "H614D / KSTP94", qualityStandards: ["Max 13.5% moisture", "EAS 40"], packaging: ["90kg Bags", "Bulk Trucks"], certifications: ["KEBS EAS 40", "NCPB Grading"], exportRequirements: ["NCPB Export Permit", "Phytosanitary Certificate"], tonsPerYear: "3500000", exportRoutes: ["Nairobi → Kampala", "Kisumu → Dar es Salaam"], avgDeliveryDays: 3, costPerTon: "45", opportunityScore: 65, suggestedAcreage: "100", yieldProjectionTons: "500", revenueProjectionUsd: "38000" },
    { name: "Tea (Black)", category: "Beverages", avgPrice: "280", currency: "KES", demandLevel: "High", marketSizeUsd: "650000000", topBuyers: ["Unilever", "Twinings", "Ahmad Tea", "Mombasa Tea Auction"], trend: "stable", marketHealth: "Green", region: "Kericho", isExport: true, isOrganic: false, priceChange7d: "0.3", priceChange30d: "1.9", globalPrice: "2200", demandGrowthPercent: "3", importRegions: ["UK", "Pakistan", "Egypt", "UAE"], exportRegions: ["Kenya", "Uganda", "Tanzania", "Rwanda"], variety: "AHP / SFS / Purple Tea", qualityStandards: ["BFOP / GFOP Grade", "Mombasa Auction Grade A"], packaging: ["54kg Paper Sacks", "Chests", "Tea Bags"], certifications: ["Rainforest Alliance", "ISO 3720", "UTZ"], exportRequirements: ["KTDA Export Permit", "Phytosanitary", "Quality Certificate"], tonsPerYear: "430000", exportRoutes: ["Mombasa Auction", "Mombasa → Karachi", "Nairobi → London"], avgDeliveryDays: 25, costPerTon: "180", opportunityScore: 71, suggestedAcreage: "15", yieldProjectionTons: "22", revenueProjectionUsd: "75000" },
    { name: "Flowers (Roses)", category: "Floriculture", avgPrice: "22", currency: "KES", demandLevel: "Very High", marketSizeUsd: "780000000", topBuyers: ["Dümmen Orange", "Kenflora", "FloraHolland", "Rosen Tantau"], trend: "up", marketHealth: "Green", region: "Naivasha", isExport: true, isOrganic: false, priceChange7d: "5.4", priceChange30d: "18.6", globalPrice: "95", demandGrowthPercent: "14", importRegions: ["Netherlands", "Germany", "France", "UK", "Japan"], exportRegions: ["Kenya", "Ethiopia", "Tanzania"], variety: "Hybrid Tea / Spray Roses", qualityStandards: ["FloraHolland Grade A1", "Stem length 60-90cm"], packaging: ["Bunch of 20", "Box 200 stems"], certifications: ["MPS-SQ", "Fairtrade", "GlobalGAP"], exportRequirements: ["KEPHIS Certificate", "Phytosanitary", "COO"], tonsPerYear: "180000", exportRoutes: ["Nairobi → Amsterdam", "Nairobi → Heathrow", "Nairobi → Addis → Frankfurt"], avgDeliveryDays: 2, costPerTon: "520", opportunityScore: 86, suggestedAcreage: "8", yieldProjectionTons: "24", revenueProjectionUsd: "148000" },
    { name: "Vanilla", category: "Spices", avgPrice: "24000", currency: "KES", demandLevel: "Very High", marketSizeUsd: "45000000", topBuyers: ["McCormick", "IFF", "Symrise", "Prova"], trend: "up", marketHealth: "Green", region: "Coastal Kenya", isExport: true, isOrganic: true, priceChange7d: "8.2", priceChange30d: "24.5", globalPrice: "120000", demandGrowthPercent: "32", importRegions: ["USA", "France", "Germany", "Japan"], exportRegions: ["Kenya", "Uganda", "Tanzania"], variety: "Planifolia / Tahitensis", qualityStandards: ["Min 20cm pod", "Min 25% vanillin"], packaging: ["1kg Vacuum Sealed", "Bulk 25kg"], certifications: ["Organic EU", "USDA Organic", "Fair Trade"], exportRequirements: ["KEPHIS Phytosanitary", "Organic Certificate", "COO"], tonsPerYear: "120", exportRoutes: ["Nairobi → Paris", "Nairobi → New York"], avgDeliveryDays: 4, costPerTon: "85000", opportunityScore: 97, suggestedAcreage: "3", yieldProjectionTons: "1.2", revenueProjectionUsd: "195000" },
    { name: "Tilapia (Fish)", category: "Aquaculture", avgPrice: "320", currency: "KES", demandLevel: "High", marketSizeUsd: "290000000", topBuyers: ["Carrefour Kenya", "Naivas", "Chandarana", "Tuskys"], trend: "up", marketHealth: "Green", region: "Lake Victoria", isExport: false, isOrganic: false, priceChange7d: "2.4", priceChange30d: "7.8", globalPrice: "850", demandGrowthPercent: "16", importRegions: ["Kenya Domestic", "Uganda", "Tanzania", "DRC"], exportRegions: ["Kenya", "Uganda", "Tanzania"], variety: "Nile Tilapia / Blue Tilapia", qualityStandards: ["Min 300g", "KEBS KS1768"], packaging: ["Whole Chilled", "Fillet Vacuum Packed"], certifications: ["KEBS", "KEPHIS", "ISO 22000"], exportRequirements: ["Health Certificate", "Export Permit"], tonsPerYear: "85000", exportRoutes: ["Lake Victoria → Nairobi", "Kisumu → Kampala"], avgDeliveryDays: 1, costPerTon: "380", opportunityScore: 78, suggestedAcreage: "2", yieldProjectionTons: "48", revenueProjectionUsd: "62000" },
  ]).returning({ id: commoditiesTable.id });

  // Price history for first 3 commodities
  console.log("Adding price history...");
  const months = ["Jan 24", "Feb 24", "Mar 24", "Apr 24", "May 24", "Jun 24", "Jul 24", "Aug 24", "Sep 24", "Oct 24", "Nov 24", "Dec 24", "Jan 25", "Feb 25", "Mar 25"];
  const avocadoPrices = [145, 152, 160, 155, 170, 178, 182, 175, 168, 172, 180, 185, 175, 182, 180];
  const coffeePrices = [820, 845, 880, 910, 895, 925, 940, 960, 945, 950, 980, 1010, 960, 975, 950];
  const macaPrices = [560, 580, 610, 595, 625, 645, 660, 680, 670, 685, 700, 720, 695, 710, 680];

  if (commodityIds.length >= 3) {
    const histData = [
      ...months.map((d, i) => ({ commodityId: commodityIds[0].id, date: d, price: avocadoPrices[i].toString() })),
      ...months.map((d, i) => ({ commodityId: commodityIds[1].id, date: d, price: coffeePrices[i].toString() })),
      ...months.map((d, i) => ({ commodityId: commodityIds[2].id, date: d, price: macaPrices[i].toString() })),
    ];
    await db.insert(priceHistoryTable).values(histData).onConflictDoNothing();
  }

  // Buyers
  console.log("Adding buyers...");
  await db.insert(buyersTable).values([
    { name: "Greenyard Fresh NL", location: "Rotterdam, Netherlands", type: "Exporter", weeklyDemandTons: "280", monthlyDemandTons: "1120", yearlyDemandTons: "13440", sustainabilityScore: 88, aiMatchScore: 94, tradeReadiness: "Ready", currency: "EUR", commodities: ["Avocado", "French Beans", "Mangoes"], isAiRecommended: true },
    { name: "Nakumatt International", location: "Nairobi, Kenya", type: "Retail", weeklyDemandTons: "145", monthlyDemandTons: "580", yearlyDemandTons: "6960", sustainabilityScore: 72, aiMatchScore: 88, tradeReadiness: "Ready", currency: "KES", commodities: ["Avocado", "Milk", "French Beans", "Maize"], isAiRecommended: true },
    { name: "Starbucks Coffee Procurement", location: "Seattle, USA", type: "Platform", weeklyDemandTons: "420", monthlyDemandTons: "1680", yearlyDemandTons: "20160", sustainabilityScore: 92, aiMatchScore: 76, tradeReadiness: "Ready", currency: "USD", commodities: ["Coffee"], isAiRecommended: false },
    { name: "Dubai Multi Commodities Centre", location: "Dubai, UAE", type: "Exporter", weeklyDemandTons: "380", monthlyDemandTons: "1520", yearlyDemandTons: "18240", sustainabilityScore: 68, aiMatchScore: 82, tradeReadiness: "Ready", currency: "USD", commodities: ["Avocado", "Flowers", "Macadamia", "Tea"], isAiRecommended: true },
    { name: "FloraHolland Auction", location: "Aalsmeer, Netherlands", type: "Platform", weeklyDemandTons: "920", monthlyDemandTons: "3680", yearlyDemandTons: "44160", sustainabilityScore: 85, aiMatchScore: 91, tradeReadiness: "Ready", currency: "EUR", commodities: ["Flowers"], isAiRecommended: true },
    { name: "Carrefour Kenya", location: "Nairobi, Kenya", type: "Retail", weeklyDemandTons: "95", monthlyDemandTons: "380", yearlyDemandTons: "4560", sustainabilityScore: 76, aiMatchScore: 85, tradeReadiness: "Ready", currency: "KES", commodities: ["Avocado", "Fish", "French Beans", "Vanilla"], isAiRecommended: false },
    { name: "McCormick & Company", location: "Maryland, USA", type: "Processor", weeklyDemandTons: "12", monthlyDemandTons: "48", yearlyDemandTons: "576", sustainabilityScore: 90, aiMatchScore: 97, tradeReadiness: "Ready", currency: "USD", commodities: ["Vanilla", "Spices"], isAiRecommended: true },
    { name: "Unilever Tea Kenya", location: "Kericho, Kenya", type: "Processor", weeklyDemandTons: "1200", monthlyDemandTons: "4800", yearlyDemandTons: "57600", sustainabilityScore: 94, aiMatchScore: 78, tradeReadiness: "Ready", currency: "KES", commodities: ["Tea"], isAiRecommended: false },
    { name: "Mauna Loa Macadamia", location: "Hawaii, USA", type: "Processor", weeklyDemandTons: "45", monthlyDemandTons: "180", yearlyDemandTons: "2160", sustainabilityScore: 82, aiMatchScore: 89, tradeReadiness: "Partial", currency: "USD", commodities: ["Macadamia"], isAiRecommended: true },
    { name: "WFP Regional Office", location: "Nairobi, Kenya", type: "Distributor", weeklyDemandTons: "2400", monthlyDemandTons: "9600", yearlyDemandTons: "115200", sustainabilityScore: 95, aiMatchScore: 70, tradeReadiness: "Ready", currency: "USD", commodities: ["Maize", "Beans", "Sorghum"], isAiRecommended: false },
  ]).onConflictDoNothing();

  // Market Alerts
  console.log("Adding market alerts...");
  await db.insert(marketAlertsTable).values([
    { type: "price_spike", commodity: "Avocado (Hass)", message: "Avocado prices surged 12% in EU markets driven by Mexico supply disruption. Kenya exporters can capitalize on $850/ton premium.", severity: "high", region: "Central Kenya" },
    { type: "high_demand", commodity: "Vanilla", message: "Global vanilla demand at 5-year high. Pure vanilla extract shortage reported by 3 major fragrance companies. Supply gap: 800 tons.", severity: "critical", region: "Coastal Kenya" },
    { type: "forecast", commodity: "Coffee (Arabica)", message: "Brazilian frost forecast to reduce 2025 global supply by 8%. Kenya AA prices expected to reach KES 1,100/kg by Q3 2025.", severity: "medium", region: "Central Kenya" },
    { type: "supply_gap", commodity: "Flowers (Roses)", message: "Dutch rose imports down 15% ahead of Valentine's Day. Kenya growers have 6-week window to fill €18M supply gap.", severity: "high", region: "Naivasha" },
    { type: "high_demand", commodity: "Macadamia", message: "Chinese consumer demand for macadamia growing 22% YoY. 3 new Chinese importers seeking direct Kenya supplier partnerships.", severity: "high", region: "Mt. Kenya" },
    { type: "price_spike", commodity: "Maize", message: "Regional maize prices up 18% following below-average long rains harvest. WFP activated emergency procurement.", severity: "critical", region: "Western Kenya" },
    { type: "forecast", commodity: "Tea (Black)", message: "Pakistan import demand growing. New trade agreement expected to increase Kenya tea quota by 40,000 tons in 2025.", severity: "medium", region: "Kericho" },
    { type: "supply_gap", commodity: "French Beans", message: "UK supermarket supply chain disruption. 3 major buyers seeking urgent alternative suppliers for July-August window.", severity: "high", region: "Central Kenya" },
  ]).onConflictDoNothing();

  // Opportunities
  console.log("Adding opportunities...");
  await db.insert(opportunitiesTable).values([
    { title: "Avocado Cold Chain Infrastructure Fund", description: "Investment opportunity to build 5 cold storage facilities across Central Kenya and Rift Valley to reduce post-harvest losses and extend export windows. Expected 340% ROI over 7 years.", type: "investment", sector: "Horticulture", roi: "34% IRR", fundingAmount: "4500000", currency: "USD", deadline: "2025-06-30", status: "open", tags: ["cold chain", "avocado", "infrastructure"] },
    { title: "EA Coffee Cooperative Digitization Grant", description: "AfDB grant program for coffee cooperatives adopting digital traceability systems, smart contract payments, and market price transparency tools.", type: "grant", sector: "Coffee", fundingAmount: "250000", currency: "USD", deadline: "2025-05-15", status: "open", tags: ["coffee", "digitization", "cooperative"] },
    { title: "Flower Export Expansion Program", description: "KEPROBA co-investment program for floriculture farms expanding production and direct-to-auction capability. Matching grants up to $150K.", type: "funding", sector: "Floriculture", roi: "22% annual", fundingAmount: "150000", currency: "USD", deadline: "2025-08-01", status: "open", tags: ["flowers", "export", "matching grant"] },
    { title: "Vanilla Value Chain Project – Coastal Kenya", description: "End-to-end vanilla value chain development: from plantation establishment to curing facility to direct buyer contracts with 3 European fragrance houses.", type: "value_chain", sector: "Spices", roi: "185% over 5 years", fundingAmount: "1200000", currency: "USD", status: "open", tags: ["vanilla", "value chain", "coastal"] },
    { title: "EAAPA Agri-Accelerator – Cohort 6", description: "12-week accelerator for high-growth agribusinesses. Participants receive $25K seed funding, mentorship, and investor introductions. Applications now open.", type: "accelerator", sector: "Multiple", fundingAmount: "25000", currency: "USD", deadline: "2025-04-30", status: "open", tags: ["accelerator", "startup", "funding"] },
    { title: "Lake Victoria Aquaculture Scale-Up", description: "Impact investment fund targeting cage aquaculture expansion on Lake Victoria. Target: 10,000 tons/year tilapia production by 2027.", type: "investment", sector: "Aquaculture", roi: "28% IRR", fundingAmount: "8000000", currency: "USD", status: "open", tags: ["fish", "aquaculture", "lake victoria"] },
    { title: "Macadamia Processing Plant – Mt. Kenya", description: "Greenfield investment in a 5,000 MT/year macadamia processing facility with Chinese export partnerships pre-arranged. Seeking strategic co-investors.", type: "investment", sector: "Tree Nuts", roi: "41% IRR", fundingAmount: "6500000", currency: "USD", deadline: "2025-09-30", status: "open", tags: ["macadamia", "processing", "china"] },
    { title: "Youth Agripreneur Incubation – East Africa", description: "IFC-backed incubation program for 18-35 year olds in agribusiness. 18-month program with working capital loans, mentorship, and market linkage.", type: "incubator", sector: "Multiple", fundingAmount: "50000", currency: "USD", deadline: "2025-07-15", status: "closing_soon", tags: ["youth", "incubation", "IFC"] },
  ]).onConflictDoNothing();

  // Projects
  console.log("Adding projects...");
  await db.insert(projectsTable).values([
    { title: "EA Avocado Export Consortium", description: "Joint project linking 200 certified avocado farmers with European buyers. Shared cold chain, certification costs, and market intelligence.", leader: "Amara Nkosi", leaderId: 1, status: "active", commodity: "Avocado", region: "Central Kenya", startDate: "2024-09-01", memberCount: 47, tags: ["avocado", "export", "consortium"] },
    { title: "Banana Processing Value Chain – Uganda", description: "Establishing a banana wine, chips, and flour processing cooperative in Central Uganda connecting 500 smallholder farmers.", leader: "Grace Atuhaire", leaderId: 3, status: "active", commodity: "Banana", region: "Central Uganda", startDate: "2025-01-15", memberCount: 23, tags: ["banana", "processing", "uganda"] },
    { title: "Digital Coffee Traceability Network", description: "Blockchain-based coffee traceability system for Rwanda, Kenya, and Ethiopia cooperatives to command specialty price premiums.", leader: "Jean-Pierre Nziza", leaderId: 6, status: "planning", commodity: "Coffee", region: "East Africa", startDate: "2025-04-01", memberCount: 12, tags: ["coffee", "blockchain", "traceability"] },
    { title: "Lake Victoria Fish Value Chain", description: "Integrated cold chain and processing project for tilapia farmers on Lake Victoria, targeting hotel and supermarket supply contracts.", leader: "Charles Mutua", leaderId: 10, status: "active", commodity: "Fish", region: "Lake Victoria Basin", startDate: "2024-11-01", memberCount: 31, tags: ["fish", "cold chain", "aquaculture"] },
    { title: "Vanilla Curing Cooperative – Coastal Kenya", description: "Establishing shared vanilla curing and storage facilities for 80 vanilla farmers to produce export-grade product collectively.", leader: "Asha Daud", leaderId: 11, status: "planning", commodity: "Vanilla", region: "Coastal Kenya", startDate: "2025-06-01", memberCount: 8, tags: ["vanilla", "cooperative", "coastal"] },
    { title: "East Africa Organic Certification Hub", description: "Collective certification program for 1,000+ smallholder farmers to access EU Organic premium markets across multiple commodities.", leader: "Zawadi Mwangi", leaderId: 13, status: "planning", commodity: "Multiple", region: "East Africa", startDate: "2025-05-01", memberCount: 19, tags: ["organic", "certification", "EU"] },
  ]).onConflictDoNothing();

  // Forum Threads
  console.log("Adding forum threads...");
  await db.insert(forumThreadsTable).values([
    { title: "Best practices for avocado export certification – GlobalGAP experience", content: "I recently completed GlobalGAP certification for my 80-acre avocado farm. Happy to share the 18-month journey, key costs (approx $4,500 for farm + audit), and lessons learned. AMA!", category: "marketing", author: "Amara Nkosi", authorId: 1, replies: 34, views: 892, tags: ["avocado", "globalGAP", "certification"] },
    { title: "Impact investor looking for dairy sector opportunities in Rift Valley", content: "We are a Nairobi-based impact investment fund with $2M allocated for the dairy value chain. Looking for processors, cooperatives, and cold chain innovators. DM or reply here.", category: "funding", author: "Samuel Kariuki", authorId: 4, replies: 28, views: 1245, tags: ["dairy", "investment", "funding"] },
    { title: "Vanilla cultivation guide for coastal Kenya smallholders", content: "After 4 years growing vanilla in Kwale, I've compiled a complete growing guide: site selection, pollination timing, curing methods, and buyer contacts. Sharing freely with EAAPA community.", category: "agronomy", author: "Asha Daud", authorId: 11, replies: 67, views: 2340, tags: ["vanilla", "guide", "coastal"] },
    { title: "Coffee prices at Nairobi auction – weekly update thread", content: "Starting a weekly thread to share Nairobi coffee auction prices. This week: AA: KES 985, AB: KES 920, PB: KES 870. Share your regional prices below.", category: "market", author: "Jean-Pierre Nziza", authorId: 6, replies: 145, views: 4820, tags: ["coffee", "prices", "auction"] },
    { title: "Youth agripreneurs: challenges accessing land for farming?", content: "I'm researching land access barriers for young agripreneurs aged 18-30. Please share your experience – are inheritance, lease markets, or cooperative models working for you?", category: "youth", author: "Moses Wanjala", authorId: 8, replies: 52, views: 1680, tags: ["youth", "land", "barriers"] },
    { title: "Digital tools for precision farming – what are you using?", content: "Beyond basic weather apps, what precision agriculture tools are actually working on your farm? I've tried Apollo Agriculture, Tulaa, and DigiFarm – sharing results.", category: "technology", author: "Peter Kamau", authorId: 15, replies: 41, views: 2190, tags: ["technology", "precision farming", "tools"] },
  ]).onConflictDoNothing();

  // Events
  console.log("Adding events...");
  await db.insert(eventsTable).values([
    { title: "EAAPA Annual Summit 2025", description: "The flagship annual gathering of East African agripreneurs, investors, and policymakers. 3-day summit with keynotes, B2B meetings, market tours, and the EAAPA Awards ceremony.", type: "conference", location: "Kenyatta International Convention Centre", country: "Kenya", startDate: "2025-05-14", endDate: "2025-05-16", registrationDeadline: "2025-04-30", attendees: 1240, maxAttendees: 2000, isFeatured: true, tags: ["summit", "annual", "networking"] },
    { title: "Agri-Export Masterclass – EU Market Entry", description: "Intensive 2-day workshop on exporting agricultural products to the EU. Covers compliance, logistics, buyer relationships, and pricing strategies.", type: "workshop", location: "Sarova Panafric Hotel, Nairobi", country: "Kenya", startDate: "2025-04-22", endDate: "2025-04-23", registrationDeadline: "2025-04-15", attendees: 89, maxAttendees: 120, isFeatured: true, tags: ["export", "EU", "workshop"] },
    { title: "East Africa Agri-Investment Forum", description: "High-level forum connecting impact investors, DFIs, and commercial banks with bankable agricultural projects across East Africa.", type: "conference", location: "Kampala Serena Hotel", country: "Uganda", startDate: "2025-06-10", endDate: "2025-06-11", registrationDeadline: "2025-05-31", attendees: 320, maxAttendees: 500, isFeatured: false, tags: ["investment", "finance", "DFI"] },
    { title: "Nairobi International Trade Fair – Agriculture Pavilion", description: "EAAPA is hosting a dedicated agriculture pavilion at the Nairobi International Trade Fair. Showcase your products to 80,000+ visitors.", type: "exhibition", location: "Jamhuri Park, Nairobi", country: "Kenya", startDate: "2025-09-26", endDate: "2025-10-06", registrationDeadline: "2025-09-01", attendees: 680, maxAttendees: 1200, isFeatured: false, tags: ["trade fair", "exhibition", "showcase"] },
    { title: "Coffee Quality & Cupping Workshop", description: "Learn coffee grading, cupping protocol, and quality assessment from Q-Graders. Practical hands-on session for coffee producers and cooperatives.", type: "training", location: "Rwanda Agriculture Board, Kigali", country: "Rwanda", startDate: "2025-04-08", endDate: "2025-04-08", registrationDeadline: "2025-04-01", attendees: 32, maxAttendees: 40, isFeatured: false, tags: ["coffee", "quality", "cupping"] },
    { title: "Horticultural Export Compliance Webinar", description: "Online session covering MaxResidue Level regulations, phytosanitary requirements, and packaging standards for EU and UK markets.", type: "webinar", location: "Online (Zoom)", country: "Kenya", startDate: "2025-04-03", endDate: "2025-04-03", registrationDeadline: "2025-04-02", attendees: 215, maxAttendees: 500, isFeatured: false, tags: ["compliance", "horticulture", "EU", "UK"] },
  ]).onConflictDoNothing();

  // Resources
  console.log("Adding resources...");
  await db.insert(resourcesTable).values([
    { title: "East Africa Agricultural Export Guide 2025", description: "Comprehensive 180-page guide covering export regulations, market entry strategies, logistics, and buyer directories for all major EA agricultural commodities.", category: "research", fileType: "PDF", fileSize: "8.4 MB", author: "EAAPA Research Team", publishedAt: "2025-01-15", downloads: 1840, tags: ["export", "guide", "2025"] },
    { title: "Avocado Production Best Practices Manual", description: "Technical guide for Hass avocado cultivation: site selection, planting, irrigation, pest management, harvesting standards, and post-harvest handling.", category: "best_practice", fileType: "PDF", fileSize: "5.2 MB", author: "Dr. Jane Waweru, Egerton University", publishedAt: "2024-08-20", downloads: 2340, tags: ["avocado", "production", "technical"] },
    { title: "Climate-Smart Agriculture in East Africa", description: "Research report on climate adaptation strategies for smallholder farmers, including drought-resistant varieties, water harvesting, and agroforestry.", category: "research", fileType: "PDF", fileSize: "12.1 MB", author: "ICRAF & CIMMYT", publishedAt: "2024-11-30", downloads: 3120, tags: ["climate", "adaptation", "smallholder"] },
    { title: "GlobalGAP Certification Step-by-Step Guide", description: "Practical farmer-friendly guide to obtaining GlobalGAP certification: checklist, timeline, costs, and certified auditor contacts for East Africa.", category: "training", fileType: "PDF", fileSize: "3.8 MB", author: "EAAPA Training Unit", publishedAt: "2024-06-01", downloads: 4850, tags: ["GlobalGAP", "certification", "training"] },
    { title: "Kenya Agricultural Policy Framework 2025-2030", description: "Official government policy framework covering subsidy programs, market infrastructure investments, and regulatory changes affecting agribusinesses.", category: "policy", fileType: "PDF", fileSize: "6.7 MB", author: "Ministry of Agriculture, Kenya", publishedAt: "2025-02-28", downloads: 980, tags: ["policy", "Kenya", "government"] },
    { title: "East Africa Commodity Price Report – Q1 2025", description: "Quarterly market intelligence report covering price trends, supply outlook, and demand forecasts for 40+ agricultural commodities across East Africa.", category: "market_report", fileType: "PDF", fileSize: "9.3 MB", author: "EAAPA Market Intelligence Unit", publishedAt: "2025-03-15", downloads: 2680, tags: ["prices", "market", "quarterly"] },
  ]).onConflictDoNothing();

  // Success Stories
  console.log("Adding success stories...");
  await db.insert(successStoriesTable).values([
    { agripreneurName: "Amara Nkosi", title: "From 5 Acres to 200: How EAAPA Unlocked EU Avocado Markets", story: "In 2018, Amara Nkosi was farming avocados on a small 5-acre plot in Murang'a with no clear market. Through EAAPA's accelerator program, she connected with Dutch buyers, secured GlobalGAP certification, and scaled to 200 acres through land lease agreements with neighboring farmers. Today, she exports 1,200 tons annually to Greenyard Fresh.", sector: "Horticulture", region: "Central Kenya", country: "Kenya", revenueUsd: 480000, jobsCreated: 85, growthPercent: 2400, commodities: ["Avocado"], publishedAt: "2024-09-15" },
    { agripreneurName: "Jean-Pierre Nziza", title: "Rwanda's Specialty Coffee Renaissance: A Cooperative Story", story: "Starting with a 2-hectare family coffee farm, Jean-Pierre connected with premium coffee buyers through EAAPA's Market Hub. He organized a cooperative of 150 farmers, built a central processing station with EAAPA investor connections, and achieved Cup scores above 87 – placing his coffee in Nespresso's Grand Cru line.", sector: "Coffee", region: "Kigali", country: "Rwanda", revenueUsd: 280000, jobsCreated: 38, growthPercent: 550, commodities: ["Coffee"], publishedAt: "2024-07-22" },
    { agripreneurName: "Tigist Bekele", title: "Flowers That Built a School: Tigist's Community Enterprise", story: "Tigist Bekele transformed a 3-hectare family plot near Ziway into a world-class floriculture operation. With EAAPA mentorship and introductions to FloraHolland, she now employs 210 workers – predominantly women – and has built a primary school and health clinic from business profits.", sector: "Floriculture", region: "Addis Ababa", country: "Ethiopia", revenueUsd: 395000, jobsCreated: 210, growthPercent: 670, commodities: ["Flowers"], publishedAt: "2024-11-08" },
    { agripreneurName: "Asha Daud", title: "Kenya's Vanilla Gold: From Coastal Village to Global Markets", story: "Asha discovered vanilla's potential for coastal Kenya after EAAPA's market intelligence showed a global supply gap. Working with 45 fellow farmers, she established a vanilla curing cooperative, obtained USDA Organic certification, and now supplies McCormick and two French fragrance houses at premium prices.", sector: "Spices", region: "Coastal Kenya", country: "Kenya", revenueUsd: 220000, jobsCreated: 18, growthPercent: 890, commodities: ["Vanilla"], publishedAt: "2025-01-20" },
  ]).onConflictDoNothing();

  // Mentors
  console.log("Adding mentors...");
  await db.insert(mentorsTable).values([
    { name: "Fatuma Hassan", expertise: ["Export Market Entry", "EU Compliance", "Buyer Negotiations", "Value Chain Development"], sector: "Export Markets", country: "Kenya", bio: "20 years in agricultural export trade. Former Director at Kenya National Trading Corporation. Has facilitated $180M in agricultural export deals across East Africa.", menteeCount: 42, rating: 48, isAvailable: true },
    { name: "Benedicte Uwimana", expertise: ["Coffee Value Chains", "Cooperative Development", "Agri-Finance", "Impact Measurement"], sector: "Coffee", country: "Rwanda", bio: "18 years with World Bank and UN FAO. Coffee cooperative development specialist who has supported 12 cooperatives achieve specialty certification and premium market access.", menteeCount: 28, rating: 50, isAvailable: true },
    { name: "Dr. James Opiyo", expertise: ["Precision Agriculture", "Soil Science", "Irrigation Systems", "Crop Nutrition"], sector: "Agronomy", country: "Kenya", bio: "PhD Soil Science from Wageningen University. 15 years in agricultural research and extension. Specializes in high-value horticulture production systems for East Africa.", menteeCount: 35, rating: 47, isAvailable: true },
    { name: "Amina Abdullahi", expertise: ["Microfinance", "Agricultural Credit", "SACCO Management", "Financial Literacy"], sector: "Finance", country: "Somalia", bio: "Pioneered mobile-based agricultural lending for pastoral communities. Has disbursed over $12M in agricultural micro-loans with 94% repayment rate.", menteeCount: 56, rating: 49, isAvailable: false },
    { name: "Prof. Samuel Gichuru", expertise: ["Agricultural Policy", "Trade Negotiations", "Market Systems", "Food Security"], sector: "Policy", country: "Kenya", bio: "Former Chief Agricultural Economist at African Development Bank. Expert in East African agricultural trade policy and WTO negotiations.", menteeCount: 19, rating: 50, isAvailable: true },
  ]).onConflictDoNothing();

  // Knowledge Items
  console.log("Adding knowledge items...");
  await db.insert(knowledgeTable).values([
    { title: "How to Negotiate Directly with European Supermarket Buyers", description: "Practical guide covering buyer meeting preparation, HACCP documentation requirements, pricing strategy, and how to handle the annual price negotiation cycle with UK and EU retailers.", category: "market_trends", tags: ["buyers", "negotiation", "EU"], views: 3420, author: "Fatuma Hassan", publishedAt: "2025-02-10" },
    { title: "Integrated Pest Management for Avocado Orchards", description: "Evidence-based IPM guide for controlling thrips, spider mites, and anthracnose in Hass avocado. Covers biological controls, approved chemical interventions, and GlobalGAP compliance.", category: "agronomy", tags: ["avocado", "IPM", "GlobalGAP"], views: 2890, author: "Dr. James Opiyo", publishedAt: "2024-12-05" },
    { title: "Blockchain for Coffee Traceability: Practical Guide for Cooperatives", description: "Step-by-step implementation guide for coffee cooperatives to adopt blockchain traceability. Covers technology selection, farmer onboarding, buyer integration, and cost-benefit analysis.", category: "technology", tags: ["coffee", "blockchain", "cooperative"], views: 1980, author: "Peter Kamau", publishedAt: "2025-01-28" },
    { title: "Understanding Currency Risk in Agricultural Exports", description: "Guide for agripreneurs on managing foreign exchange exposure in export contracts. Covers forward contracts, natural hedging, and pricing strategies in KES, USD, and EUR.", category: "finance", tags: ["currency", "export", "risk"], views: 2240, author: "Samuel Kariuki", publishedAt: "2025-03-01" },
    { title: "East Africa Climate Forecast 2025: Impact on Key Commodities", description: "EAAPA's seasonal climate forecast and its projected impact on avocado, coffee, maize, and tea production across Kenya, Uganda, Tanzania, and Ethiopia.", category: "market_trends", tags: ["climate", "forecast", "production"], views: 4680, author: "EAAPA Research Team", publishedAt: "2025-03-10" },
  ]).onConflictDoNothing();

  console.log("✅ EAAPA database seeded successfully!");
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
